### ISSUE TITLE
Add copy to clipboard option

### ISSUE THREAD

**Issue by HarshitRV** [HarshitRV/FileShare#7]

**Comment by MarinJursic** [comment]
Give the `<a>` tag on line 22 an id ( I've put filelink as an example )

Add a button

`<button onClick="handlecopy()">Copy to clipboard</button>`

Add a script

```
handleCopy() {
    const copyText = document.getElementById("filelink").getAttribute("href");
    navigator.clipboard.writeText(copyText);
 }

```

**Comment by HarshitRV** [comment]
Thanks for the help @MarinJursic.
Resolved in [commit](https://github.com/HarshitRV/FileShare/commit/5070e5a4cad97894502d198cce86ed18097c9a70)
